INSERT INTO tb_category (name) VALUES ('Tecnologia');
INSERT INTO tb_category (name) VALUES ('Educação');
INSERT INTO tb_category (name) VALUES ('Saúde');
INSERT INTO tb_category (name) VALUES ('Esportes');
INSERT INTO tb_category (name) VALUES ('Entretenimento');
INSERT INTO tb_category (name) VALUES ('Negócios');
INSERT INTO tb_category (name) VALUES ('Ciência');
INSERT INTO tb_category (name) VALUES ('Moda');
INSERT INTO tb_category (name) VALUES ('Culinária');
INSERT INTO tb_category (name) VALUES ('Viagens');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Smartphone X1', 'Smartphone de última geração com IA integrada', 2999.90, 'https://example.com/img1.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Notebook Pro', 'Notebook potente para programação e design', 5499.00, 'https://example.com/img2.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Fone Bluetooth Z', 'Fone sem fio com cancelamento de ruído', 499.90, 'https://example.com/img3.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Roteador Gamer', 'Roteador de alta performance para jogos', 799.00, 'https://example.com/img4.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Curso de Java', 'Curso completo de Java com projetos práticos', 199.90, 'https://example.com/img5.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Apostila ENEM 2025', 'Apostila atualizada para o ENEM', 49.90, 'https://example.com/img6.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Curso de Inglês', 'Curso online de inglês para iniciantes', 99.90, 'https://example.com/img7.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Curso de Design Gráfico', 'Aprenda Photoshop e Illustrator', 149.90, 'https://example.com/img8.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Suplemento Whey', 'Suplemento proteico para treino', 119.90, 'https://example.com/img9.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Bicicleta Ergométrica', 'Aparelho de exercício para casa', 999.90, 'https://example.com/img10.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Smartwatch Saúde', 'Relógio inteligente com monitor de batimentos', 299.00, 'https://example.com/img11.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Oxímetro Portátil', 'Mede a saturação de oxigênio no sangue', 79.90, 'https://example.com/img12.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Camisa de Time', 'Camisa oficial do time 2025', 249.90, 'https://example.com/img13.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Bola Oficial', 'Bola de futebol profissional', 199.90, 'https://example.com/img14.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Tênis Esportivo', 'Tênis leve e confortável para corrida', 349.90, 'https://example.com/img15.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Kit Academia', 'Kit com halteres, tapete e corda', 399.90, 'https://example.com/img16.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Assinatura Streaming', 'Plataforma de filmes e séries', 29.90, 'https://example.com/img17.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Console Game X', 'Console de última geração', 3999.00, 'https://example.com/img18.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Fone Gamer', 'Fone com microfone e som surround', 499.90, 'https://example.com/img19.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Controle sem fio', 'Controle de videogame', 249.90, 'https://example.com/img20.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Livro Empreendedorismo', 'Guia para abrir seu próprio negócio', 59.90, 'https://example.com/img21.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Planilha Financeira', 'Template Excel para controle de gastos', 9.90, 'https://example.com/img22.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Curso de Marketing', 'Curso com certificado incluso', 199.90, 'https://example.com/img23.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Software ERP', 'Sistema de gestão empresarial', 1299.90, 'https://example.com/img24.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Microscópio Portátil', 'Para experimentos científicos em casa', 499.90, 'https://example.com/img25.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Livro de Física', 'Livro didático atualizado', 89.90, 'https://example.com/img26.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Curso de Astronomia', 'Explore o universo', 149.90, 'https://example.com/img27.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Kits de Química', 'Kit de experiências para crianças', 199.90, 'https://example.com/img28.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Vestido Floral', 'Vestido leve e moderno', 179.90, 'https://example.com/img29.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Tênis Casual', 'Confortável para o dia a dia', 229.90, 'https://example.com/img30.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Relógio Fashion', 'Design moderno e elegante', 319.90, 'https://example.com/img31.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Bolsa Feminina', 'Estilo e praticidade', 249.90, 'https://example.com/img32.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Livro de Receitas', 'Mais de 200 receitas práticas', 49.90, 'https://example.com/img33.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Kit de Panelas', 'Jogo completo antiaderente', 299.90, 'https://example.com/img34.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Batedeira Planetária', 'Alta performance na cozinha', 449.90, 'https://example.com/img35.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Avental Personalizado', 'Para chefs de cozinha', 39.90, 'https://example.com/img36.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Guia de Viagem Europa', 'Dicas de roteiros e hospedagens', 89.90, 'https://example.com/img37.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Mochila de Viagem', 'Resistente e espaçosa', 199.90, 'https://example.com/img38.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Câmera Fotográfica', 'Alta resolução para suas aventuras', 1499.90, 'https://example.com/img39.jpg');
INSERT INTO tb_product (name, description, price, img_url) VALUES ('Power Bank Solar', 'Carregue seus dispositivos em qualquer lugar', 129.90, 'https://example.com/img40.jpg');
INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (26, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (27, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (28, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (29, 8);
INSERT INTO tb_product_category (product_id, category_id) VALUES (30, 8);
INSERT INTO tb_product_category (product_id, category_id) VALUES (31, 8);
INSERT INTO tb_product_category (product_id, category_id) VALUES (32, 8);
INSERT INTO tb_product_category (product_id, category_id) VALUES (33, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (34, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (35, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (36, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (37, 10);
INSERT INTO tb_product_category (product_id, category_id) VALUES (38, 10);
INSERT INTO tb_product_category (product_id, category_id) VALUES (39, 10);
INSERT INTO tb_product_category (product_id, category_id) VALUES (40, 10);
